project:
  type: book
  output-dir: _book

book:
  title: "Fundamentals in Data Management for Qualitative and Quantitative Arctic Research"
  # author: "Arctic Data Center"
  # date: today
  # date-format: iso
  chapters:
    - index.qmd
    - intro.qmd
    - open-data-reproducibility.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

