# Open Data and Reproducibility

## Learning Objectives

-   Shared understanding of open and research reproducibility

-   Introduction to computational reproducibility

-   Introduction to FAIR and CARE as they relate to open data

-   Familiarity with metadata best practices

## What is open science and research reproducibility?

Throughout this course you will hear us emphasize open practices and research reproducibility. Indeed, as a data repository charged with both preserving and making accessible the products of NSF funded research, it is no surprise that these topics are central to our mission. However, these terms, while readily parsed, can mean different things to different individuals depending on their frame of reference and research activities. Further, even with a shared definition variation exists in the degree to which openness and research reproducibility can (or should) be implemented.

Before we begin, we are going to take the time to discuss and possibly develop a shared understanding of the terms 'open' and 'reproducible' as they pertain to research.
